SELECT * FROM CLIENT_ACCOUNT WHERE (CLIENT_ID) IN
(
    SELECT CLIENT_ACCOUNT.CLIENT_ID AS [Client Id], CLIENT.SURNAME AS [Client Surname], CLIENT_ACCOUNT.CLIENT_ACCOUNT_NUMBER AS [Client Account Number], ACCOUNT_TYPE.DESCRIPTION AS [Account Description], MAX(CLIENT_ACCOUNT.DISPLAY_BALANCE) AS [Display Balance]
    FROM CLIENT_ACCOUNT
    INNER JOIN CLIENT ON CLIENT_ACCOUNT.CLIENT_ID = CLIENT.CLIENT_ID
    INNER JOIN ACCOUNT_TYPE ON CLIENT_ACCOUNT.ACCOUNT_TYPE_CODE = ACCOUNT_TYPE.ACCOUNT_TYPE_CODE AND ACCOUNT_TYPE.TRANSACTIONAL = 1
    GROUP BY CLIENT_ID
)